version: '3.7'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 5430:5432

  web:
    build:
      context: ./
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

volumes:
  database-storage: